changelog:
  exclude:
    labels:
      - ignore-for-release-notes
  categories:
    - title: New Features 🎉
      labels:
        - new-feature
    - title: Bug fixes 🛠
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
