name: Create release

on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "REPO_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" >> $GITHUB_ENV
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Bundle documentation theme
        run: npm run bundle
      - name: Change bundle name
        run: mv build/ui-bundle.zip build/bonita-documentation-theme-${{ env.RELEASE_VERSION }}.zip
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "build/bonita-documentation-theme-${{ env.RELEASE_VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.JC_TOKEN }}
          repository: ${{ env.REPO_NAME }}
          event-type: new_theme_bundle
          client-payload: '{"release": "${{ env.RELEASE_VERSION }}", "release_notes_url": "${{ env.REPO_URL }}/releases/tag/${{ env.RELEASE_VERSION }}", "bundle_file": "bonita-documentation-theme-${{ env.RELEASE_VERSION }}.zip", "bundle_url": "${{ env.REPO_URL }}/releases/download/${{ env.RELEASE_VERSION }}/bonita-documentation-theme-${{ env.RELEASE_VERSION }}.zip"}'
